# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Homepage-online-ordering-section"
  description: Online ordering section of home page
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  mainImgSm: ""
  mainImgLg: ""
  mainImgAlt: ""
  category: ""
  mainHeading: ""
  mainContent: ""
  mainContent2: ""
  link_to_COD_nonCreditAccountForm: ""
  link_to_OnlineOrderForm: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
