paths:
  uploads: assets/uploads
  data: _data
  layouts: _includes/layouts
  includes: _includes
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true
  primary:
    type: color
    label: Primary Color
    cascade: true
    default: '#1d3c6b'
  primary_dark:
    type: color
    label: Primary Dark Color
    cascade: true
    default: '#0d192b'
  primary_text:
    type: color
    label: Primary Text Color
    cascade: true
    default: '#5a5e63'
  light_text:
    type: color
    label: Light Text Color
    cascade: true
    default: '#787cad'
  dark_text:
    type: color
    label: Dark Text Color
    cascade: true
    default: '#242424'
  on_dark_text:
    type: color
    label: On Dark Text Color
    cascade: true
    default: '#ffffff'
  dark_border:
    type: color
    label: Dark Border Color
    cascade: true
    default: '#aca8d4'
  light_border:
    type: color
    label: Light Border Color
    cascade: true
    default: '#e0e0e0'
  background:
    type: color
    label: Background Color
    cascade: true
    default: '#eef3f7'
  bright_background:
    type: color
    label: Bright Background Color
    cascade: true
    default: '#ffffff'
  soft_highlight:
    type: color
    label: Soft Highlight Color
    cascade: true
    default: '#f5f5f5'
  link:
    type: color
    label: Link Color
    cascade: true
    default: '#000000'
  logo:
    type: image
    label: Logo
    cascade: true
  image.url:
    type: image
    cascade: true
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting: true
    italic: true
    link: true
    paths:
    redo:
    removeformat:
    strike:
    subscript:
    superscript:
    underline:
    undo:
data_config: {}
timezone: US/Eastern
